//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhChon
    {
        public int MaBinhChon { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string NoiDung { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
